/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OurBricksJPanel.java
 *
 * Created on 26-Jul-2011, 11:29:03
 */

package org.jdesktop.wonderland.modules.ourbricks.client;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import org.jdesktop.wonderland.client.jme.dnd.URLDataFlavorHandler;
import org.jdesktop.wonderland.modules.ourbricks.client.ourbricks.OurBricksList;

/**
 *
 * @author jos
 */
public class OurBricksJPanel extends javax.swing.JPanel {

    private OurBricksList bricksList;;
    private JButton[] buttonArray = new JButton[5];
    private JLabel[] labelArray = new JLabel[5];

    /** Creates new form OurBricksJPanel */
    public OurBricksJPanel() {
        
        initComponents();
        search(null, null);
        
    }

    private void search(String query, Integer next){
        try {
            bricksList = OurBricksDataProvider.requestDataFromExternalService(query, next); //On error just return an empty list for now.
        } catch (MalformedURLException ex) {
            Logger.getLogger(OurBricksJPanel.class.getName()).log(Level.SEVERE, null, ex);
            bricksList = new OurBricksList();
        } catch (IOException ex) {
            Logger.getLogger(OurBricksJPanel.class.getName()).log(Level.SEVERE, null, ex);
            bricksList = new OurBricksList();
        }
        addButtonsAndLabelsToArray();
        OurBricksDataProvider.setButtonData(bricksList, buttonArray, labelArray);
        enableNavigation();
    }

    private void searchFromOffset(Integer offset){
        System.out.println("The value of searchTextField.getText() is : " + searchTextField.getText());
        //TODO deal with http://ourbricks.com/api/search?q=truck&start=1&limit=5
        if (searchTextField.getText() == null || searchTextField.getText().equals(""))
            search(null, offset);
        else
            search(searchTextField.getText(), offset);
    }

    /**
     * Adding all buttons to and array so that they can be manipulated automatically
     */
    private void addButtonsAndLabelsToArray(){
        buttonArray[0] = jButton1; buttonArray[1] = jButton2; buttonArray[2] = jButton3;
        buttonArray[3] = jButton4; buttonArray[4] = jButton5;

        labelArray[0] = jLabel1; labelArray[1] = jLabel2; labelArray[2] = jLabel3;
        labelArray[3] = jLabel4; labelArray[4] = jLabel5;
    }

    private void enableNavigation(){
        
        if (bricksList.getNext_start() != null){
            next.setEnabled(true);
        }
        else {
            next.setEnabled(false);
        }

        if (bricksList.getPrev_start() != null){
            previous.setEnabled(true);
        }
        else {
            previous.setEnabled(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelSearch = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        allModels = new javax.swing.JButton();

        setAutoscrolls(true);

        jButton2.setText("jButton2");
        jButton2.setMaximumSize(new java.awt.Dimension(200, 133));
        jButton2.setMinimumSize(new java.awt.Dimension(200, 133));
        jButton2.setPreferredSize(new java.awt.Dimension(200, 133));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.setMaximumSize(new java.awt.Dimension(200, 133));
        jButton3.setMinimumSize(new java.awt.Dimension(200, 133));
        jButton3.setPreferredSize(new java.awt.Dimension(200, 133));

        jButton4.setText("jButton4");
        jButton4.setMaximumSize(new java.awt.Dimension(200, 133));
        jButton4.setMinimumSize(new java.awt.Dimension(200, 133));
        jButton4.setPreferredSize(new java.awt.Dimension(200, 133));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.setMaximumSize(new java.awt.Dimension(200, 133));
        jButton5.setMinimumSize(new java.awt.Dimension(200, 133));
        jButton5.setPreferredSize(new java.awt.Dimension(200, 133));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.setMaximumSize(new java.awt.Dimension(200, 133));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 133));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 133));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelSearch.setText("Search for Models:");

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("no model found");

        jLabel2.setText("no model found");

        jLabel3.setText("no model found");

        jLabel4.setText("no model found");

        jLabel5.setText("no model found");

        allModels.setText("All Models");
        allModels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allModelsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addGap(105, 105, 105)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(previous))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(next)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allModels)
                        .addGap(208, 208, 208))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {next, previous});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSearch)
                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(allModels))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previous)
                    .addComponent(next))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //TODO Change the harcoded item numbers
        downloadModel( bricksList.getItems().get(0).getDownload_link() );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //TODO Change the harcoded item numbers
        downloadModel( bricksList.getItems().get(1).getDownload_link() );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        handleSearch();
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        handleSearch();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        searchFromOffset(bricksList.getPrev_start());
    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        searchFromOffset(bricksList.getNext_start());
    }//GEN-LAST:event_nextActionPerformed

    private void allModelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allModelsActionPerformed
        searchTextField.setText("");
        search(null, null);
    }//GEN-LAST:event_allModelsActionPerformed

    private void handleSearch(){
        if ( searchTextField.getText() != null && !searchTextField.getText().equals("")) {
            search(searchTextField.getText(), null);
        }

    }

    private void downloadModel(String urlOfModel){
        //TODO this is no good cause the dowload is of a zip file and no cell seems
        // to handle it... ask in the forum and check the snapshot code
        try {
//            URLDataFlavorHandler.launchCellFromURL( new URL(urlOfModel) );
        }
        catch (Exception e){
            //TODO HANDLE ME NOW!!!!!!!!!!!!!!
            //Malformed URL Exceptiopn and IOException
            Logger.getLogger(OurBricksJPanel.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allModels;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JButton next;
    private javax.swing.JButton previous;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables

}
